let data = [
  {
    id: "2",
    unternehmen:
      "Amt f\u00fcr Statistik Berlin-Brandenburg Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "0",
    anteil: "50",
    bilanzsumme: "28,41",
    eigenkapital: "1,67",
    umsatz: "48,46",
    jahresergebnis: "0,59",
    zufuehrungen: "21,94",
    investitionen: "0,55",
    beschaeftigte: "482",
    anschrift: "Steinstra\u00dfe 104 - 106, 14480 Potsdam",
    internet: "www.statistik-berlin-brandenburg.de",
    logo: "statistikbbteaser.gif",
    geschaeftsfuehrung: "B\u00f6mermann, Hartmut\nFidorra, J\u00f6rg",
    kontrollgremienvorsitz: "Fischer, Rolf",
  },
  {
    id: "5",
    unternehmen: "BBB Infrastruktur GmbH & Co. KG",
    nominalkapital: "17",
    anteil: "100",
    bilanzsumme: "97,93",
    eigenkapital: "91,86",
    umsatz: "1,52",
    jahresergebnis: "4,2",
    zufuehrungen: "0,1",
    investitionen: "0,44",
    beschaeftigte: "0",
    anschrift: "Sachsendamm 2-4, 10829 Berlin",
    internet: "www.berlinerbaeder.de",
    logo: "bbbinfrateaser.gif",
    geschaeftsfuehrung: "Komplement\u00e4rin",
    kontrollgremienvorsitz: "entf\u00e4llt",
  },
  {
    id: "8",
    unternehmen: "BBB Infrastruktur-Verwaltungs GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "0,03",
    eigenkapital: "0,03",
    umsatz: "0,01",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "2",
    anschrift: "Sachsendamm 2-4, 10829 Berlin",
    internet: "www.berlinerbaeder.de",
    logo: "bbbinfrateaser.gif",
    geschaeftsfuehrung: "Kleinsorg, Johannes, Dr.\nRupprecht, Marie",
    kontrollgremienvorsitz: "Spranger, Iris",
  },
  {
    id: "11",
    unternehmen: "BEHALA - Berliner Hafen- und Lagerhausgesellschaft mbH",
    nominalkapital: "21",
    anteil: "100",
    bilanzsumme: "94,1",
    eigenkapital: "52,19",
    umsatz: "20,52",
    jahresergebnis: "1,45",
    zufuehrungen: "0",
    investitionen: "2,64",
    beschaeftigte: "128",
    anschrift: "Westhafenstra\u00dfe 1, 13353 Berlin",
    internet: "www.behala.de",
    logo: "behalateaser.gif",
    geschaeftsfuehrung: "Cardinal, Petra",
    kontrollgremienvorsitz: "Schopf, Tino",
  },
  {
    id: "14",
    unternehmen: "BEN Berlin Energie und Netzholding GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "3.170,40",
    eigenkapital: "0",
    umsatz: "574,8",
    jahresergebnis: "-8",
    zufuehrungen: "2",
    investitionen: "138,6",
    beschaeftigte: "1575",
    anschrift: "Columbiadamm 10, D2, 12101 Berlin",
    internet: "www.be-nh.de",
    logo: "",
    geschaeftsfuehrung: "Neldner, Wolfgang",
    kontrollgremienvorsitz: "Schopf, Tino",
  },
  {
    id: "17",
    unternehmen: "Berlin Tourismus & Kongress GmbH",
    nominalkapital: "0,51",
    anteil: "15",
    bilanzsumme: "6,74",
    eigenkapital: "0,77",
    umsatz: "4,45",
    jahresergebnis: "-0,01",
    zufuehrungen: "17,76",
    investitionen: "0,45",
    beschaeftigte: "183",
    anschrift: "Am Karlsbad 11, 10785 Berlin",
    internet: "www.visitBerlin.de",
    logo: "visitberlinteaser.gif",
    geschaeftsfuehrung: "Kieker, Burkhard",
    kontrollgremienvorsitz: "Schumacher, Oliver",
  },
  {
    id: "20",
    unternehmen:
      "Berliner B\u00e4der-Betriebe (BBB) Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "46,21",
    eigenkapital: "0",
    umsatz: "89,26",
    jahresergebnis: "-0,63",
    zufuehrungen: "73,23",
    investitionen: "5,81",
    beschaeftigte: "792",
    anschrift: "Sachsendamm , 10829 Berlin",
    internet: "www.berlinerbaeder.de",
    logo: "bbbteaser.gif",
    geschaeftsfuehrung: "Kleinsorg, Johannes, Dr.\nRupprecht, Marie",
    kontrollgremienvorsitz: "Spranger, Iris",
  },
  {
    id: "23",
    unternehmen:
      "Berliner Energieagentur Gesellschaft mit beschr\u00e4nkter Haftung",
    nominalkapital: "2,56",
    anteil: "25",
    bilanzsumme: "21,22",
    eigenkapital: "7,94",
    umsatz: "14,64",
    jahresergebnis: "0,53",
    zufuehrungen: "0",
    investitionen: "1,08",
    beschaeftigte: "50",
    anschrift: "Fasanenstra\u00dfe 85, 10623 Berlin",
    internet: "www.berliner-e-agentur.de",
    logo: "blnenergieagenturteaser.gif",
    geschaeftsfuehrung: "Gei\u00dfler, Michael",
    kontrollgremienvorsitz: "Schopf, Tino",
  },
  {
    id: "26",
    unternehmen: "Berliner Gro\u00dfmarkt GmbH",
    nominalkapital: "24,8",
    anteil: "100",
    bilanzsumme: "54,43",
    eigenkapital: "36,57",
    umsatz: "13,4",
    jahresergebnis: "2,14",
    zufuehrungen: "0",
    investitionen: "0,31",
    beschaeftigte: "28",
    anschrift: "Beusselstra\u00dfe 44 n - q, 10553 Berlin",
    internet: "www.berliner-grossmarkt.de",
    logo: "bmgmarktteaser.gif",
    geschaeftsfuehrung: "Cardinal, Petra",
    kontrollgremienvorsitz: "Schopf, Tino",
  },
  {
    id: "29",
    unternehmen: "Berliner Stadtg\u00fcter GmbH",
    nominalkapital: "10,15",
    anteil: "100",
    bilanzsumme: "88,86",
    eigenkapital: "68,23",
    umsatz: "9,54",
    jahresergebnis: "3,37",
    zufuehrungen: "0",
    investitionen: "6,61",
    beschaeftigte: "52",
    anschrift: "Frankfurter Allee 73 c, 10247 Berlin",
    internet: "www.berlinerstadtgueter.de",
    logo: "blnstadtgueterteaser.gif",
    geschaeftsfuehrung: "Stary, Katrin",
    kontrollgremienvorsitz: "Rhode-M\u00fchlenhoff, Heidrun",
  },
  {
    id: "32",
    unternehmen:
      "Berliner Stadtreinigungsbetriebe (BSR) Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "153,39",
    anteil: "100",
    bilanzsumme: "907,13",
    eigenkapital: "174,45",
    umsatz: "766,21",
    jahresergebnis: "38,36",
    zufuehrungen: "0",
    investitionen: "60,36",
    beschaeftigte: "6660",
    anschrift: "Ringbahnstra\u00dfe 96, 12103 Berlin",
    internet: "www.bsr.de",
    logo: "bsrteaser.gif",
    geschaeftsfuehrung: "Urban, Martin\nKehren, Werner\nOtto, Stephanie",
    kontrollgremienvorsitz: "Schwarz, Stephan",
  },
  {
    id: "35",
    unternehmen:
      "Berliner Verkehrsbetriebe (BVG) Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "2.560,00",
    anteil: "100",
    bilanzsumme: "6.087,97",
    eigenkapital: "1.477,71",
    umsatz: "1.297,88",
    jahresergebnis: "3,48",
    zufuehrungen: "886,77",
    investitionen: "464,67",
    beschaeftigte: "15378",
    anschrift: "Holzmarktstra\u00dfe 15-17, 10179 Berlin",
    internet: "www.bvg.de",
    logo: "bvgteaser.gif",
    geschaeftsfuehrung: "Kreienkamp, Eva\nErfurt, Rolf, Dr.\nN.N.",
    kontrollgremienvorsitz: "Schwarz, Stephan",
  },
  {
    id: "38",
    unternehmen: "Berliner Wasserbetriebe Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "749,22",
    anteil: "100",
    bilanzsumme: "7.963,03",
    eigenkapital: "1.991,50",
    umsatz: "1.362,73",
    jahresergebnis: "198,36",
    zufuehrungen: "16,95",
    investitionen: "458,92",
    beschaeftigte: "4591",
    anschrift: "Neue J\u00fcdenstra\u00dfe 1, 10864 Berlin",
    internet: "www.bwb.de",
    logo: "berliner_wasserbetriebe_logo.jpg",
    geschaeftsfuehrung: "Bruckmann, Frank\nOster, Kerstin\nN.N.",
    kontrollgremienvorsitz: "Schwarz, Stephan",
  },
  {
    id: "41",
    unternehmen:
      "Berliner Werkst\u00e4tten f\u00fcr Menschen mit Behinderung - GmbH (BWB)",
    nominalkapital: "0,06",
    anteil: "70",
    bilanzsumme: "32,2",
    eigenkapital: "18,54",
    umsatz: "32,02",
    jahresergebnis: "2,49",
    zufuehrungen: "0",
    investitionen: "0,88",
    beschaeftigte: "1935,33",
    anschrift: "Westhafenstra\u00dfe 4, 13353 Berlin",
    internet: "www.bwb-gmbh.de",
    logo: "bwbteaser.gif",
    geschaeftsfuehrung: "Gerstle, Dirk",
    kontrollgremienvorsitz: "Pape-Wunnenberg, Wolfgang",
  },
  {
    id: "44",
    unternehmen: "Berlinovo Immobilien Gesellschaft mbH",
    nominalkapital: "0,05",
    anteil: "100",
    bilanzsumme: "4.283,08",
    eigenkapital: "2.029,31",
    umsatz: "270,28",
    jahresergebnis: "51,63",
    zufuehrungen: "0",
    investitionen: "127,4",
    beschaeftigte: "345",
    anschrift: "Hallesches Ufer 74 - 76, 10963 Berlin",
    internet: "www.berlinovo.de",
    logo: "berlinovoteaser.gif",
    geschaeftsfuehrung: "Andresen-Kienz, Silke\nAleithe, Alf Franz",
    kontrollgremienvorsitz: "Dreher, Barbro",
  },
  {
    id: "47",
    unternehmen: "Berlinwasser Holding GmbH",
    nominalkapital: "51,13",
    anteil: "100",
    bilanzsumme: "161,17",
    eigenkapital: "155,28",
    umsatz: "0,07",
    jahresergebnis: "2,26",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "2,5",
    anschrift: "Neue J\u00fcdenstra\u00dfe 1, 10179 Berlin",
    internet: "www.berlinwasser.de",
    logo: "blnwasserteaser.gif",
    geschaeftsfuehrung: "Bruckmann, Frank\nOster, Kerstin\nN.N.",
    kontrollgremienvorsitz: "Pankow, Irina",
  },
  {
    id: "50",
    unternehmen:
      "BGZ Berliner Gesellschaft f\u00fcr internationale Zusammenarbeit mbH",
    nominalkapital: "0,03",
    anteil: "60",
    bilanzsumme: "0,68",
    eigenkapital: "0,03",
    umsatz: "0",
    jahresergebnis: "0",
    zufuehrungen: "0,52",
    investitionen: "0",
    beschaeftigte: "9",
    anschrift: "Pohlstra\u00dfe 67, 10785 Berlin",
    internet: "www.bgz-berlin.de",
    logo: "bgzuteaser.gif",
    geschaeftsfuehrung: "Hansen, Hilde, Dr.",
    kontrollgremienvorsitz: "Wittke, J\u00fcrgen",
  },
  {
    id: "53",
    unternehmen: "BIM Berliner Immobilienmanagement GmbH",
    nominalkapital: "0,3",
    anteil: "100",
    bilanzsumme: "77,1",
    eigenkapital: "56,74",
    umsatz: "69,37",
    jahresergebnis: "2,79",
    zufuehrungen: "0",
    investitionen: "12,99",
    beschaeftigte: "688",
    anschrift: "Keibelstra\u00dfe 36, 10178 Berlin",
    internet: "www.bim-berlin.de",
    logo: "bimteaser.gif",
    geschaeftsfuehrung: "Lemiss, Sven\nM\u00f6hring, Birgit",
    kontrollgremienvorsitz: "Dreher, Barbro",
  },
  {
    id: "56",
    unternehmen: "Campus Berlin-Buch GmbH",
    nominalkapital: "0,03",
    anteil: "50,1",
    bilanzsumme: "26,92",
    eigenkapital: "1,3",
    umsatz: "10,71",
    jahresergebnis: "0,04",
    zufuehrungen: "0",
    investitionen: "7,44",
    beschaeftigte: "37",
    anschrift: "Robert-R\u00f6ssle-Stra\u00dfe 10, 13125 Berlin",
    internet: "www.campusberlinbuch.de",
    logo: "campusbuchteaser.gif",
    geschaeftsfuehrung: "Scheller, Ulrich, Dr.\nQuensel, Christina, Dr.",
    kontrollgremienvorsitz: "Rhode-M\u00fchlenhoff, Heidrun",
  },
  {
    id: "59",
    unternehmen:
      "DEGES Deutsche Einheit Fernstra\u00dfenplanungs- und -bau GmbH",
    nominalkapital: "0,06",
    anteil: "5,91",
    bilanzsumme: "1.182,93",
    eigenkapital: "0,15",
    umsatz: "22,07",
    jahresergebnis: "0,01",
    zufuehrungen: "0",
    investitionen: "3,15",
    beschaeftigte: "495",
    anschrift: "Zimmerstr. 54, 10117 Berlin",
    internet: "www.deges.de",
    logo: "degesteaser.jpg",
    geschaeftsfuehrung: "Brandenburger, Dirk\nFriedrich, Wolf-Dieter",
    kontrollgremienvorsitz: "Tegtbauer, Tatjana",
  },
  {
    id: "62",
    unternehmen: "degewo Aktiengesellschaft",
    nominalkapital: "145",
    anteil: "100",
    bilanzsumme: "4.844,74",
    eigenkapital: "1.514,33",
    umsatz: "531,21",
    jahresergebnis: "97,95",
    zufuehrungen: "2,61",
    investitionen: "487,22",
    beschaeftigte: "1348,1",
    anschrift: "Potsdamer Stra\u00dfe 60, 10785 Berlin",
    internet: "www.degewo.de",
    logo: "degewoteaser.gif",
    geschaeftsfuehrung: "Beck, Christoph\nWehrmann, Sandra",
    kontrollgremienvorsitz: "K\u00f6nig, Dorette",
  },
  {
    id: "65",
    unternehmen: "Deutsche Film- und Fernsehakademie Berlin, GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "2,53",
    eigenkapital: "0,02",
    umsatz: "7,07",
    jahresergebnis: "0",
    zufuehrungen: "5,48",
    investitionen: "0,36",
    beschaeftigte: "70",
    anschrift: "Potsdamer Stra\u00dfe 2, 10785 Berlin",
    internet: "www.dffb.de",
    logo: "dffbteaser.gif",
    geschaeftsfuehrung: "Berger, Catherine Ann\nWilke, Marie",
    kontrollgremienvorsitz: "Fischer, Severin, Dr.",
  },
  {
    id: "68",
    unternehmen:
      "Deutsche Klassenlotterie Berlin rechtsf\u00e4hige Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "10,23",
    anteil: "100",
    bilanzsumme: "92,31",
    eigenkapital: "40,68",
    umsatz: "256,85",
    jahresergebnis: "5,19",
    zufuehrungen: "0",
    investitionen: "1,29",
    beschaeftigte: "162",
    anschrift: "Brandenburgische Stra\u00dfe 36, 10707 Berlin",
    internet: "www.lotto-berlin.de",
    logo: "lottoteaser.gif",
    geschaeftsfuehrung:
      "H\u00f6ltkemeier, Hansj\u00f6rg\nBle\u00df, Marion, Dr.",
    kontrollgremienvorsitz: "Fischer, Severin, Dr.",
  },
  {
    id: "71",
    unternehmen:
      "Deutsches Zentrum f\u00fcr Hochschul- und Wissenschaftsforschung GmbH",
    nominalkapital: "0,03",
    anteil: "1,85",
    bilanzsumme: "9,95",
    eigenkapital: "0,15",
    umsatz: "0",
    jahresergebnis: "-0,01",
    zufuehrungen: "0,12",
    investitionen: "0,1",
    beschaeftigte: "244",
    anschrift: "Lange Laube 12, 30159 Hannover",
    internet: "www.dzhw.eu",
    logo: "dzhwteaser.jpg",
    geschaeftsfuehrung:
      "Jungbauer-Gans, Monika, Prof. Dr.\nKowalke, Thorsten, Dr.",
    kontrollgremienvorsitz: "Greisler, Peter",
  },
  {
    id: "74",
    unternehmen:
      "Ferdinand-Braun-Institut gGmbH, Leibniz-Institut f\u00fcr H\u00f6chstfrequenztechnik",
    nominalkapital: "0,04",
    anteil: "100",
    bilanzsumme: "77,14",
    eigenkapital: "0,04",
    umsatz: "0",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "8,61",
    beschaeftigte: "300",
    anschrift: "Gustav-Kirchhoff-Stra\u00dfe 4, 12489 Berlin",
    internet: "www.fbh-berlin.de",
    logo: "",
    geschaeftsfuehrung:
      "Tr\u00e4nkle, G\u00fcnther, Prof. Dr.\nEiermann, Karin-Irene, Dr.",
    kontrollgremienvorsitz: "Lietzau, Bernd",
  },
  {
    id: "77",
    unternehmen: "Flughafen Berlin Brandenburg GmbH",
    nominalkapital: "11",
    anteil: "37",
    bilanzsumme: "5.308,19",
    eigenkapital: "0",
    umsatz: "271,72",
    jahresergebnis: "-569,06",
    zufuehrungen: "0",
    investitionen: "168,73",
    beschaeftigte: "2154",
    anschrift: "Flughafen Berlin Brandenburg, 12521 Berlin",
    internet: "www.berlin-airport.de",
    logo: "blnflughafenteaser.gif",
    geschaeftsfuehrung:
      "Halberstadt, Michael\nvon Massenbach, Aletta\nHoff Andersson, Thomas",
    kontrollgremienvorsitz: "Simon, J\u00f6rg",
  },
  {
    id: "80",
    unternehmen: "Friedrichstadt-Palast Betriebsgesellschaft mbH",
    nominalkapital: "0,51",
    anteil: "100",
    bilanzsumme: "18,43",
    eigenkapital: "8,29",
    umsatz: "10,85",
    jahresergebnis: "0",
    zufuehrungen: "24,77",
    investitionen: "5,92",
    beschaeftigte: "328",
    anschrift: "Friedrichstra\u00dfe 107, 10117 Berlin",
    internet: "www.palast.berlin",
    logo: "friedrichstadtpalastteaser.gif",
    geschaeftsfuehrung: "Schmidt, Berndt, Dr.",
    kontrollgremienvorsitz: "Lederer, Klaus, Dr.",
  },
  {
    id: "83",
    unternehmen:
      "FWU Institut f\u00fcr Film und Bild in Wissenschaft und Unterricht gemeinn\u00fctzige GmbH",
    nominalkapital: "0,16",
    anteil: "6,25",
    bilanzsumme: "3,75",
    eigenkapital: "1,29",
    umsatz: "5,93",
    jahresergebnis: "0,05",
    zufuehrungen: "0,02",
    investitionen: "1,08",
    beschaeftigte: "48,25",
    anschrift: "Bavariafilmplatz 3, 82031 Gr\u00fcnwald",
    internet: "www.fwu.de",
    logo: "medieninstitutteaser.gif",
    geschaeftsfuehrung: "Nill, R\u00fcdiger\nFrost, Michael",
    kontrollgremienvorsitz: "Altmeyer, Gabriele",
  },
  {
    id: "86",
    unternehmen: "GESOBAU AG",
    nominalkapital: "78,27",
    anteil: "100",
    bilanzsumme: "2.833,24",
    eigenkapital: "637,74",
    umsatz: "316,8",
    jahresergebnis: "45,78",
    zufuehrungen: "0,61",
    investitionen: "340,29",
    beschaeftigte: "449,72",
    anschrift: "Stiftsweg 1, 13187 Berlin",
    internet: "www.gesobau.de",
    logo: "gesobauteaser.gif",
    geschaeftsfuehrung: "Franzen, J\u00f6rg\nWilkens, Christian",
    kontrollgremienvorsitz: "Galley, Birgit",
  },
  {
    id: "89",
    unternehmen: "Gewobag Wohnungsbau-Aktiengesellschaft Berlin",
    nominalkapital: "84,46",
    anteil: "96,69",
    bilanzsumme: "5.770,98",
    eigenkapital: "213,39",
    umsatz: "550,87",
    jahresergebnis: "23,03",
    zufuehrungen: "4,25",
    investitionen: "379,13",
    beschaeftigte: "690,71",
    anschrift: "Alt-Moabit 101 A, 10559 Berlin",
    internet: "www.gewobag.de",
    logo: "gewobagteaser.gif",
    geschaeftsfuehrung: "Terboven, Markus\nMichaelis, Snezana",
    kontrollgremienvorsitz: "Brummer-Kohler, Anke",
  },
  {
    id: "92",
    unternehmen: "Gr\u00fcn Berlin GmbH",
    nominalkapital: "0,05",
    anteil: "100",
    bilanzsumme: "97,61",
    eigenkapital: "0,05",
    umsatz: "10,06",
    jahresergebnis: "0",
    zufuehrungen: "39,37",
    investitionen: "8,68",
    beschaeftigte: "182",
    anschrift: "Mariendorfer Damm 1, 12099 Berlin",
    internet: "www.gruen-berlin.de",
    logo: "gruenberlinteaser.gif",
    geschaeftsfuehrung: "Schmidt, Christoph",
    kontrollgremienvorsitz: "Karcher, Silke, Dr.",
  },
  {
    id: "95",
    unternehmen: "Hebbel-Theater Berlin GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "3,67",
    eigenkapital: "1,34",
    umsatz: "0,49",
    jahresergebnis: "0",
    zufuehrungen: "8,45",
    investitionen: "0,42",
    beschaeftigte: "57",
    anschrift: "Stresemannstra\u00dfe 29, 10963 Berlin",
    internet: "www.hebbel-am-ufer.de",
    logo: "hauteaser.gif",
    geschaeftsfuehrung: "Vanackere, Annemie",
    kontrollgremienvorsitz: "W\u00f6hlert, Torsten, Dr.",
  },
  {
    id: "98",
    unternehmen:
      "Helmholtz-Zentrum Berlin f\u00fcr Materialien und Energie GmbH",
    nominalkapital: "0,4",
    anteil: "10",
    bilanzsumme: "593,67",
    eigenkapital: "0,95",
    umsatz: "9,32",
    jahresergebnis: "-0,04",
    zufuehrungen: "20,1",
    investitionen: "36,4",
    beschaeftigte: "1246",
    anschrift: "Hahn-Meitner-Platz 1, 14109 Berlin",
    internet: "www.helmholtz-berlin.de",
    logo: "hzbteaser.gif",
    geschaeftsfuehrung:
      "Frederking, Thomas\nRech, Bernd, Prof. Dr.\nL\u00fcning, Jan, Prof. Dr.",
    kontrollgremienvorsitz: "Dietz, Volkmar, Dr.",
  },
  {
    id: "101",
    unternehmen: "HOWOGE Wohnungsbaugesellschaft mit beschr\u00e4nkter Haftung",
    nominalkapital: "25",
    anteil: "100",
    bilanzsumme: "5.649,12",
    eigenkapital: "1.776,40",
    umsatz: "429,51",
    jahresergebnis: "49,14",
    zufuehrungen: "0,09",
    investitionen: "491,86",
    beschaeftigte: "850,51",
    anschrift: "Stefan-Heym-Platz 1, 10367 Berlin",
    internet: "www.howoge.de",
    logo: "howogeteaser.gif",
    geschaeftsfuehrung: "Felgenhauer, Thomas\nSchiller, Ulrich",
    kontrollgremienvorsitz: "Jellema, Hendrik",
  },
  {
    id: "104",
    unternehmen: "IBB Unternehmensverwaltung A\u00f6R",
    nominalkapital: "750",
    anteil: "100",
    bilanzsumme: "20.807,59",
    eigenkapital: "1.110,78",
    umsatz: "81,43",
    jahresergebnis: "290,79",
    zufuehrungen: "0",
    investitionen: "2,78",
    beschaeftigte: "734",
    anschrift: "Bundesallee 210, 10719 Berlin",
    internet: "www.ibb.de",
    logo: "ibbuvteaser.jpg",
    geschaeftsfuehrung: "Krisilion, Angeliki\nHolm, Hinrich, Dr.",
    kontrollgremienvorsitz: "Schwarz, Stephan",
  },
  {
    id: "107",
    unternehmen:
      "IT-Dienstleistungszentrum Berlin Anstalt des \u00f6ffentlichen Rechts",
    nominalkapital: "65",
    anteil: "100",
    bilanzsumme: "280,01",
    eigenkapital: "164,98",
    umsatz: "414,9",
    jahresergebnis: "44,91",
    zufuehrungen: "6,07",
    investitionen: "32,98",
    beschaeftigte: "1066",
    anschrift: "Berliner Stra\u00dfe 112-115, 10713 Berlin",
    internet: "www.itdz-berlin.de",
    logo: "itdzteaser.gif",
    geschaeftsfuehrung: "B\u00f6ttcher, Marc",
    kontrollgremienvorsitz: "Kleindiek, Ralf, Dr.",
  },
  {
    id: "110",
    unternehmen:
      "Kinder- und Jugendfreizeitzentrum Wuhlheide - Landesmusikakademie - gemeinn\u00fctzige Betriebsgesellschaft mbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "1,1",
    eigenkapital: "0,05",
    umsatz: "0,94",
    jahresergebnis: "-0,01",
    zufuehrungen: "7,92",
    investitionen: "0,3",
    beschaeftigte: "129",
    anschrift: "Stra\u00dfe zum FEZ 2, 12459 Berlin",
    internet: "www.fez-berlin.de",
    logo: "fezteaser.gif",
    geschaeftsfuehrung: "Bergh\u00e4user, Chris\nLiljeberg-Markuse, Thomas",
    kontrollgremienvorsitz: "Bozkurt, Aziz",
  },
  {
    id: "113",
    unternehmen: "Kulturprojekte Berlin GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "2,24",
    eigenkapital: "0,3",
    umsatz: "1,24",
    jahresergebnis: "0,04",
    zufuehrungen: "12,19",
    investitionen: "0,08",
    beschaeftigte: "90",
    anschrift: "Klosterstra\u00dfe 68, 10179 Berlin",
    internet: "www.kulturprojekte-berlin.de",
    logo: "kulturprojekteteaser.gif",
    geschaeftsfuehrung: "van D\u00fclmen, Moritz",
    kontrollgremienvorsitz: "Lederer, Klaus, Dr.",
  },
  {
    id: "116",
    unternehmen:
      "Kunst- und Ausstellungshalle der Bundesrepublik Deutschland GmbH",
    nominalkapital: "0,04",
    anteil: "2,44",
    bilanzsumme: "2,04",
    eigenkapital: "0,04",
    umsatz: "0,95",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "113",
    anschrift: "Helmut-Kohl-Allee 4, 53113 Bonn",
    internet: "www.bundeskunsthalle.de",
    logo: "kunsthalleteaser.gif",
    geschaeftsfuehrung: "Kraus, Eva-Christina, Dr.\nH\u00f6lken, Oliver",
    kontrollgremienvorsitz: "Winands, G\u00fcnter, Dr.",
  },
  {
    id: "119",
    unternehmen: "Liegenschaftsfonds Berlin GmbH & Co. KG",
    nominalkapital: "1",
    anteil: "100",
    bilanzsumme: "1,34",
    eigenkapital: "1,28",
    umsatz: "0,04",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "0",
    anschrift: "Keibelstr. 36, 10178 Berlin",
    internet: "",
    logo: "liegenschaftsfondsteaser.gif",
    geschaeftsfuehrung: "Komplement\u00e4rin",
    kontrollgremienvorsitz: "entf\u00e4llt",
  },
  {
    id: "122",
    unternehmen: "Liegenschaftsfonds Berlin Projektgesellschaft mbH & Co. KG",
    nominalkapital: "0,1",
    anteil: "100",
    bilanzsumme: "0,13",
    eigenkapital: "0,1",
    umsatz: "0,01",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "0",
    anschrift: "Keibelstr. 36, 10178 Berlin",
    internet: "",
    logo: "liegenschaftsfondsteaser.gif",
    geschaeftsfuehrung: "Komplement\u00e4rin",
    kontrollgremienvorsitz: "entf\u00e4llt",
  },
  {
    id: "125",
    unternehmen: "Liegenschaftsfonds Berlin Verwaltungsgesellschaft mbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "0,08",
    eigenkapital: "0,06",
    umsatz: "0,02",
    jahresergebnis: "0",
    zufuehrungen: "0",
    investitionen: "0",
    beschaeftigte: "2",
    anschrift: "Keibelstr. 36, 10176 Berlin",
    internet: "",
    logo: "liegenschaftsfondsteaser.gif",
    geschaeftsfuehrung: "M\u00f6hring, Birgit\nLemiss, Sven",
    kontrollgremienvorsitz: "Dreher, Barbro",
  },
  {
    id: "128",
    unternehmen:
      "MEAB M\u00e4rkische Entsorgungsanlagen-Betriebsgesellschaft mbH",
    nominalkapital: "25,6",
    anteil: "50",
    bilanzsumme: "471,79",
    eigenkapital: "124,28",
    umsatz: "49,09",
    jahresergebnis: "6,69",
    zufuehrungen: "0",
    investitionen: "4,16",
    beschaeftigte: "176",
    anschrift: "Tschudistra\u00dfe 3, 14476 Potsdam",
    internet: "www.meab.de",
    logo: "meabteaser.gif",
    geschaeftsfuehrung: "Mattat, Frank",
    kontrollgremienvorsitz: "Tag, Jaqueline",
  },
  {
    id: "131",
    unternehmen: "Messe Berlin GmbH",
    nominalkapital: "20,71",
    anteil: "100",
    bilanzsumme: "352,94",
    eigenkapital: "36,8",
    umsatz: "161,46",
    jahresergebnis: "4,13",
    zufuehrungen: "0",
    investitionen: "6,54",
    beschaeftigte: "897",
    anschrift: "Messedamm 22, 14055 Berlin",
    internet: "www.messe-berlin.de",
    logo: "messeteaser.gif",
    geschaeftsfuehrung: "Ecknig, Martin\nHoffmann, Dirk",
    kontrollgremienvorsitz: "N.N.",
  },
  {
    id: "134",
    unternehmen: "Musicboard Berlin GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "0,18",
    eigenkapital: "0,03",
    umsatz: "0,29",
    jahresergebnis: "0",
    zufuehrungen: "0,76",
    investitionen: "0,01",
    beschaeftigte: "10,36",
    anschrift: "Gerichtstr. 35, 13347 Berlin",
    internet: "www.musicboard-berlin.de",
    logo: "mbbteaser.jpg",
    geschaeftsfuehrung: "Lucker, Katja",
    kontrollgremienvorsitz: "Lederer, Klaus, Dr.",
  },
  {
    id: "137",
    unternehmen: "Olympiastadion Berlin GmbH",
    nominalkapital: "0,5",
    anteil: "100",
    bilanzsumme: "11,38",
    eigenkapital: "8,87",
    umsatz: "7,67",
    jahresergebnis: "-1,02",
    zufuehrungen: "0",
    investitionen: "0,06",
    beschaeftigte: "23",
    anschrift: "Olympischer Platz 3, 14053 Berlin",
    internet: "www.olympiastadion-berlin.de",
    logo: "olympiastadionteaser.gif",
    geschaeftsfuehrung: "Rohwedder, Timo",
    kontrollgremienvorsitz: "Spranger, Iris",
  },
  {
    id: "140",
    unternehmen: "Rundfunk-Orchester und -Ch\u00f6re (gemeinn\u00fctzige) GmbH",
    nominalkapital: "0,03",
    anteil: "20",
    bilanzsumme: "19,96",
    eigenkapital: "12,61",
    umsatz: "2,51",
    jahresergebnis: "6,3",
    zufuehrungen: "8,3",
    investitionen: "0,1",
    beschaeftigte: "332,91",
    anschrift: "Charlottenstra\u00dfe 56, 10117 Berlin",
    internet: "www.roc-berlin.de",
    logo: "rocteaser.gif",
    geschaeftsfuehrung: "Rose, Anselm",
    kontrollgremienvorsitz: "Elitz, Ernst, Prof.",
  },
  {
    id: "143",
    unternehmen: "SBB Sonderabfallgesellschaft Brandenburg/Berlin mbH",
    nominalkapital: "0,75",
    anteil: "25",
    bilanzsumme: "2,34",
    eigenkapital: "1,77",
    umsatz: "3,41",
    jahresergebnis: "-0,4",
    zufuehrungen: "0",
    investitionen: "0,05",
    beschaeftigte: "38,2",
    anschrift: "Gro\u00dfbeerenstra\u00dfe 231, 14480 Potsdam",
    internet: "www.sbb-mbh.de",
    logo: "sbbteaser.gif",
    geschaeftsfuehrung: "Wilkens, Berend\nBlaschey, Ariane",
    kontrollgremienvorsitz: "Ott, Susanne",
  },
  {
    id: "146",
    unternehmen:
      "STADT UND LAND Wohnbauten-Gesellschaft mit beschr\u00e4nkter Haftung",
    nominalkapital: "165,02",
    anteil: "100",
    bilanzsumme: "3.255,03",
    eigenkapital: "860,6",
    umsatz: "348,63",
    jahresergebnis: "42,62",
    zufuehrungen: "6,83",
    investitionen: "186,91",
    beschaeftigte: "642",
    anschrift: "Werbellinstra\u00dfe 12, 12053 Berlin",
    internet: "www.stadtundland.de",
    logo: "stadtundlandteaser.gif",
    geschaeftsfuehrung: "Malter, Ingo\nKlimek, Natascha",
    kontrollgremienvorsitz: "Landerer, Christoph, Dr.",
  },
  {
    id: "149",
    unternehmen: "Tegel Projekt Gesellschaft mit beschr\u00e4nkter Haftung",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "2,49",
    eigenkapital: "1,23",
    umsatz: "6,57",
    jahresergebnis: "-0,02",
    zufuehrungen: "0",
    investitionen: "0,11",
    beschaeftigte: "68",
    anschrift:
      "Urban Tech Republic, Geb\u00e4ude V, Flughafen Tegel 1, 13405 Berlin",
    internet: "www.tegelprojekt.de",
    logo: "",
    geschaeftsfuehrung: "Sack, Gudrun",
    kontrollgremienvorsitz: "Gaebler, Christian",
  },
  {
    id: "152",
    unternehmen: "Tempelhof Projekt GmbH",
    nominalkapital: "0,03",
    anteil: "100",
    bilanzsumme: "3,59",
    eigenkapital: "2,37",
    umsatz: "0",
    jahresergebnis: "0,68",
    zufuehrungen: "0",
    investitionen: "0,18",
    beschaeftigte: "80",
    anschrift: "Columbiadamm 10, A2, 12101 Berlin",
    internet: "www.thf-berlin.de",
    logo: "tempelhoferfreiheitteaser.gif",
    geschaeftsfuehrung: "Heim-Wenzler, Jutta",
    kontrollgremienvorsitz: "Kahlfeldt, Petra",
  },
  {
    id: "155",
    unternehmen: "VBB Verkehrsverbund Berlin-Brandenburg GmbH",
    nominalkapital: "0,32",
    anteil: "33,33",
    bilanzsumme: "5,46",
    eigenkapital: "0,32",
    umsatz: "0,56",
    jahresergebnis: "0",
    zufuehrungen: "5,44",
    investitionen: "0,37",
    beschaeftigte: "122",
    anschrift: "Stralauer Platz 29, 10243 Berlin",
    internet: "www.VBB.de",
    logo: "vbbteaser.gif",
    geschaeftsfuehrung: "Kuck, Andreas\nFuchs, Martin",
    kontrollgremienvorsitz: "Niedbal, Meike, Dr.",
  },
  {
    id: "158",
    unternehmen: "Vivantes - Netzwerk f\u00fcr Gesundheit GmbH",
    nominalkapital: "55",
    anteil: "100",
    bilanzsumme: "1.800,00",
    eigenkapital: "797,12",
    umsatz: "1.567,10",
    jahresergebnis: "3,27",
    zufuehrungen: "71,07",
    investitionen: "156,9",
    beschaeftigte: "13200",
    anschrift: "Aroser Allee 72-76, 13407 Berlin",
    internet: "www.vivantes.de",
    logo: "vivantesteaser.gif",
    geschaeftsfuehrung:
      "Schmidt, Dorothea\nKrahmer, Eibo, Dr.\nDanckert, Johannes, Dr.",
    kontrollgremienvorsitz: "Nagel, Eckhard, Prof. Dr.",
  },
  {
    id: "161",
    unternehmen:
      "WBM Wohnungsbaugesellschaft Berlin-Mitte mit beschr\u00e4nkter Haftung",
    nominalkapital: "6,72",
    anteil: "100",
    bilanzsumme: "2.224,35",
    eigenkapital: "832,08",
    umsatz: "261,96",
    jahresergebnis: "38,81",
    zufuehrungen: "2,41",
    investitionen: "160,96",
    beschaeftigte: "382",
    anschrift: "Dircksenstra\u00dfe 38, 10178 Berlin",
    internet: "www.wbm.de",
    logo: "wbmteaser.gif",
    geschaeftsfuehrung: "Geib, Christina\nHelbig, Steffen",
    kontrollgremienvorsitz: "Stubbe, Peter",
  },
  {
    id: "164",
    unternehmen: "Wissenschaftszentrum Berlin f\u00fcr Sozialforschung gGmbH",
    nominalkapital: "0,03",
    anteil: "25",
    bilanzsumme: "28,59",
    eigenkapital: "0,03",
    umsatz: "0,52",
    jahresergebnis: "0",
    zufuehrungen: "4,29",
    investitionen: "0,89",
    beschaeftigte: "324,56",
    anschrift: "Reichpietschufer 50, 10785 Berlin",
    internet: "www.wzb.eu",
    logo: "wzbteaser.gif",
    geschaeftsfuehrung: "Allmendinger, Jutta, Prof. Dr.\nNoack, Ursula",
    kontrollgremienvorsitz: "Sch\u00fcller, Ulrich",
  },
  {
    id: "167",
    unternehmen: "WISTA Management GmbH",
    nominalkapital: "11,78",
    anteil: "100",
    bilanzsumme: "224,12",
    eigenkapital: "80,82",
    umsatz: "27,67",
    jahresergebnis: "2,56",
    zufuehrungen: "2,34",
    investitionen: "7,06",
    beschaeftigte: "61,5",
    anschrift: "Rudower Chaussee 17, 12489 Berlin",
    internet: "www.wista.de",
    logo: "wistateaser.gif",
    geschaeftsfuehrung: "Sillmann, Roland",
    kontrollgremienvorsitz: "Biel, Michael",
  },
  {
    id: "170",
    unternehmen: "Zoologischer Garten Berlin AG",
    nominalkapital: "1,72",
    anteil: "0,03",
    bilanzsumme: "117,24",
    eigenkapital: "76,08",
    umsatz: "17,64",
    jahresergebnis: "14,72",
    zufuehrungen: "0",
    investitionen: "10,93",
    beschaeftigte: "256,67",
    anschrift: "Hardenbergplatz 8, 10787 Berlin",
    internet: "www.zoo-berlin.de",
    logo: "zooteaser.gif",
    geschaeftsfuehrung: "Knieriem, Andreas, Dr.",
    kontrollgremienvorsitz: "Bruckmann, Frank",
  },
];
